### ISSUE TITLE
Tracking not working... 

### ISSUE THREAD

**Issue by dmullaney** [bahrmichael/brave-bucks#46]
I have a bunch of kills that haven't showed up (just a sample below):
https://zkillboard.com/kill/70882582/
https://zkillboard.com/kill/70882629/
https://zkillboard.com/kill/70882570/

I tried adding them manually but I get an error: 
![bucks](https://user-images.githubusercontent.com/2980194/41937213-a410761c-7987-11e8-9064-d776ae76fe0b.jpeg)

**Comment by bahrmichael** [comment]
Thanks for reporting. I'll look into it.

**Comment by bahrmichael** [comment]
Issue identified. Patch is in the pipeline.

**Comment by bahrmichael** [comment]
Please try again now. Should be fixed.
