### ISSUE TITLE
How long does it take?

### ISSUE THREAD

**Issue by Asimov7Foundation** [bahrmichael/brave-bucks#49]
I made a request for a Brave bucks payout about 10-days ago, character Asimov7 Foundation, as of today I still haven't seen a payout. The request was for 192mil and change. How long does it take to get a payout? Are payouts on a monthly or bi-weekly cycle. The brave bucks page didn't really have any info on this and it took me a long time to find the tiny little github link at the bottom of the page to get to this site and ask a questions. As a new player (started in Feb) it was very confusing and no-one in BNI could tell me anything about it.

Thankyou for your time

**Comment by bahrmichael** [comment]
Avend handles the payouts on his own schedule. I've forwarded this message to him.

**Comment by Asimov7Foundation** [comment]
Thankyou so much!!!!
